services:
  app:
    build:
      context: .
      dockerfile: dockerfile

    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: node ./dist/main.js
