name: Node.js CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org

      - name: "Installing dependencies"
        run: cd bad-fockarch && npm install

      - name: "Building package"
        run: cd bad-fockarch && npm run build

      - name: "Publishing"
        run: cd bad-fockarch && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
