name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create zip archive
      run: |
        zip -r release.zip . -x \
          "*.git*" \
          "*.github*" \
          "node_modules/*" \
          "bad-fockarch/*"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip