name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build project (если нужно)
        run: npm install && npm run build

      - name: Prepare release files
        run: |
          mkdir -p release_contents
          cp -r dist/ README.md LICENSE release_contents/

      - name: Create tar archive
        run: |
          tar -czf "$GITHUB_WORKSPACE/release.tar.gz" -C release_contents .
          ls -lh "$GITHUB_WORKSPACE/release.tar.gz"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}