name: Create release

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/bad-fockarch/**'
      - '**/dist/**'
      - '**/node_modules/**'
      - '**/docs/**'
      - '**/pnpm-lock.yaml'
      - '**/package-lock.json'
      - '**/LICENSE'
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes