name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: |
          **/src/**
          **/test/**
          **/tsconfig.json
          **/tsconfig.build.json
          **/package.json
          **/nest-cli.json
          **/eslint.config.mjs
          **/.prettierrc
          **/.gitignore
          **/.env.example