name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare release files
        run: |
          mkdir -p release_contents
          cp -r src/

      - name: Create tar archive
        run: |
          tar -czf "$GITHUB_WORKSPACE/release.tar.gz" -C release_contents .
          ls -lh "$GITHUB_WORKSPACE/release.tar.gz"

          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes
            ./release.tar.gz